import type { Student, Teacher, Subject, Assessment } from './types';

export const teachers: Teacher[] = [
  {
    teacherId: 'T001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@campusconnect.edu',
    phone: '123-456-7890',
    assignedSubjects: ['SUB001', 'SUB002'],
  },
  {
    teacherId: 'T002',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@campusconnect.edu',
    phone: '098-765-4321',
    assignedSubjects: ['SUB003', 'SUB004'],
  },
];

export const subjects: Subject[] = [
  { subjectId: 'SUB001', subjectName: 'Mathematics', gradeLevel: '10', teacherId: 'T001' },
  { subjectId: 'SUB002', subjectName: 'Physics', gradeLevel: '10', teacherId: 'T001' },
  { subjectId: 'SUB003', subjectName: 'English Literature', gradeLevel: '10', teacherId: 'T002' },
  { subjectId: 'SUB004', subjectName: 'History', gradeLevel: '10', teacherId: 'T002' },
];

export const students: Student[] = [
  {
    studentId: 'S001',
    enrollmentDate: new Date('2023-09-01'),
    firstName: 'Liam',
    lastName: 'Johnson',
    khmerFirstName: 'លីម',
    khmerLastName: 'ចនសុន',
    sex: 'Male',
    dateOfBirth: new Date('2008-04-23'),
    placeOfBirth: 'Springfield',
    nationality: 'American',
    nationalId: 'USA123456',
    status: 'Active',
    previousSchool: 'Springfield Middle School',
    address: {
        village: 'Maplewood',
        commune: 'Springfield Heights',
        district: 'Springfield County',
    },
    guardians: [
      {
        relation: 'Father',
        name: 'Robert Johnson',
        occupation: 'Engineer',
        workplace: 'Tech Corp',
        mobiles: ['555-1112', '555-1113'],
      },
    ],
    mediaConsent: true,
    emergencyContact: { name: 'Robert Johnson', phone: '555-1112' },
    avatarUrl: 'https://picsum.photos/seed/1/100/100',
    enrollments: [{ programId: 'khmer-national', level: 'Grade 10' }],
  },
  {
    studentId: 'S002',
    enrollmentDate: new Date('2023-09-01'),
    firstName: 'Olivia',
    lastName: 'Smith',
    khmerFirstName: 'អូលីវីਆ',
    khmerLastName: 'ស្មីត',
    sex: 'Female',
    dateOfBirth: new Date('2008-08-15'),
    placeOfBirth: 'Oakville',
    nationality: 'British',
    nationalId: 'GBR654321',
    status: 'Active',
    address: {
        village: 'Oakhaven',
        commune: 'Oakville',
        district: 'Oakshire',
    },
    guardians: [
        {
            relation: 'Mother',
            name: 'Mary Smith',
            occupation: 'Doctor',
            workplace: 'General Hospital',
            mobiles: ['555-2223'],
        },
    ],
    mediaConsent: false,
    emergencyContact: { name: 'Mary Smith', phone: '555-2223' },
    avatarUrl: 'https://picsum.photos/seed/2/100/100',
    enrollments: [{ programId: 'english-international', level: 'Grade 10' }],
  },
  {
    studentId: 'S003',
    enrollmentDate: new Date('2024-01-15'),
    firstName: 'Noah',
    lastName: 'Williams',
    khmerFirstName: 'ណូអេ',
    khmerLastName: 'វីលៀមស៍',
    sex: 'Male',
    dateOfBirth: new Date('2008-01-30'),
    placeOfBirth: 'Pine Ridge',
    nationality: 'Canadian',
    nationalId: 'CAN789012',
    status: 'Active',
    address: {
        village: 'Pinegrove',
        commune: 'Pine Ridge',
        district: 'Pinedale',
    },
    guardians: [
        {
            relation: 'Father',
            name: 'James Williams',
            occupation: 'Lawyer',
            workplace: 'Williams & Co.',
            mobiles: ['555-3334'],
        },
    ],
    mediaConsent: true,
    emergencyContact: { name: 'James Williams', phone: '555-3334' },
    avatarUrl: 'https://picsum.photos/seed/3/100/100',
    enrollments: [
      { programId: 'english-international', level: 'Grade 10' },
      { programId: 'esl', level: 'Level 04' }
    ],
  },
  {
    studentId: 'S004',
    enrollmentDate: new Date('2024-02-20'),
    firstName: 'Emma',
    lastName: 'Brown',
    khmerFirstName: 'អេម៉ា',
    khmerLastName: 'ប្រោន',
    sex: 'Female',
    dateOfBirth: new Date('2008-11-12'),
    placeOfBirth: 'Birchwood',
    nationality: 'Australian',
    nationalId: 'AUS345678',
    status: 'Active',
    address: {
        village: 'Birch Creek',
        commune: 'Birchwood',
        district: 'Birch County',
    },
    guardians: [
        {
            relation: 'Mother',
            name: 'Patricia Brown',
            occupation: 'Accountant',
            workplace: 'Finance Inc.',
            mobiles: ['555-4445'],
        },
    ],
    mediaConsent: true,
    emergencyContact: { name: 'Patricia Brown', phone: '555-4445' },
    avatarUrl: 'https://picsum.photos/seed/4/100/100',
    enrollments: [{ programId: 'csl', level: 'Level 03' }],
  },
    {
    studentId: 'S005',
    enrollmentDate: new Date('2024-03-10'),
    firstName: 'Ava',
    lastName: 'Jones',
    khmerFirstName: 'អាវ៉ា',
    khmerLastName: 'ចូនស៍',
    sex: 'Female',
    dateOfBirth: new Date('2008-05-20'),
    placeOfBirth: 'Cedar Hill',
    nationality: 'American',
    nationalId: 'USA987654',
    status: 'Active',
    address: {
        village: 'Cedarville',
        commune: 'Cedar Hill',
        district: 'Cedar County',
    },
    guardians: [
        {
            relation: 'Mother',
            name: 'Jennifer Jones',
            occupation: 'Artist',
            workplace: 'Studio J',
            mobiles: ['555-5556', '555-5557'],
        },
        {
            relation: 'Father',
            name: 'David Jones',
            occupation: 'Musician',
            workplace: 'Self-employed',
            mobiles: ['555-5558'],
        }
    ],
    mediaConsent: false,
    emergencyContact: { name: 'Jennifer Jones', phone: '555-5556' },
    avatarUrl: 'https://picsum.photos/seed/5/100/100',
    enrollments: [{ programId: 'esl', level: 'Level 05' }],
  },
];


export const assessments: Assessment[] = [
  {
    assessmentId: 'A001',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Algebra Basics',
    category: 'Classwork',
    totalMarks: 25,
    scores: { 'S001': 22, 'S002': 18, 'S003': 24, 'S004': 20, 'S005': 15 },
  },
  {
    assessmentId: 'A002',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Geometry Fundamentals',
    category: 'Unit Assessment',
    totalMarks: 100,
    scores: { 'S001': 88, 'S002': 75, 'S003': 95, 'S004': 82, 'S005': 60 },
  },
  {
    assessmentId: 'A003',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Shakespearean Sonnets',
    category: 'Homework',
    totalMarks: 10,
    scores: { 'S001': 9, 'S002': 10, 'S003': 8, 'S004': 9, 'S005': 10 },
  },
  {
    assessmentId: 'A004',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Modernist Poetry',
    category: 'Unit Assessment',
    totalMarks: 100,
    scores: { 'S001': 85, 'S002': 92, 'S003': 78, 'S004': 88, 'S005': 95 },
  },
  {
    assessmentId: 'A005',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Calculus Prep',
    category: 'End-Semester',
    totalMarks: 150,
    scores: { 'S001': 130, 'S002': 110, 'S003': 145, 'S004': 120, 'S005': 95 },
  },
  {
    assessmentId: 'A006',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Victorian Novels',
    category: 'End-Semester',
    totalMarks: 150,
    scores: { 'S001': 125, 'S002': 140, 'S003': 115, 'S004': 130, 'S005': 142 },
  },
];
