import type { Student, Teacher, Subject, Assessment } from './types';

export const teachers: Teacher[] = [
  {
    teacherId: 'T001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@campusconnect.edu',
    phone: '123-456-7890',
    assignedSubjects: ['SUB001', 'SUB002'],
  },
  {
    teacherId: 'T002',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@campusconnect.edu',
    phone: '098-765-4321',
    assignedSubjects: ['SUB003', 'SUB004'],
  },
];

export const subjects: Subject[] = [
  { subjectId: 'SUB001', subjectName: 'Mathematics', gradeLevel: '10', teacherId: 'T001' },
  { subjectId: 'SUB002', subjectName: 'Physics', gradeLevel: '10', teacherId: 'T001' },
  { subjectId: 'SUB003', subjectName: 'English Literature', gradeLevel: '10', teacherId: 'T002' },
  { subjectId: 'SUB004', subjectName: 'History', gradeLevel: '10', teacherId: 'T002' },
];

export const students: Student[] = [
  {
    studentId: 'S001',
    firstName: 'Liam',
    lastName: 'Johnson',
    khmerFirstName: 'លីម',
    khmerLastName: 'ចនសុន',
    sex: 'Male',
    dateOfBirth: new Date('2008-04-23'),
    nationality: 'American',
    nationalId: 'USA123456',
    program: 'Science',
    admissionYear: 2022,
    currentGradeLevel: '10',
    status: 'Active',
    address: '123 Maple St, Springfield',
    studentEmail: 'liam.j@email.com',
    studentPhone: '555-1111',
    parentGuardianName: 'Robert Johnson',
    parentGuardianPhone: '555-1112',
    emergencyContactName: 'Robert Johnson',
    emergencyContactPhone: '555-1112',
    avatarUrl: 'https://picsum.photos/seed/1/100/100',
  },
  {
    studentId: 'S002',
    firstName: 'Olivia',
    lastName: 'Smith',
    khmerFirstName: 'អូលីវីਆ',
    khmerLastName: 'ស្មីត',
    sex: 'Female',
    dateOfBirth: new Date('2008-08-15'),
    nationality: 'British',
    nationalId: 'GBR654321',
    program: 'Arts',
    admissionYear: 2022,
    currentGradeLevel: '10',
    status: 'Active',
    address: '456 Oak Ave, Springfield',
    studentEmail: 'olivia.s@email.com',
    studentPhone: '555-2222',
    parentGuardianName: 'Mary Smith',
    parentGuardianPhone: '555-2223',
    emergencyContactName: 'Mary Smith',
    emergencyContactPhone: '555-2223',
    avatarUrl: 'https://picsum.photos/seed/2/100/100',
  },
  {
    studentId: 'S003',
    firstName: 'Noah',
    lastName: 'Williams',
    khmerFirstName: 'ណូអេ',
    khmerLastName: 'វីលៀមស៍',
    sex: 'Male',
    dateOfBirth: new Date('2008-01-30'),
    nationality: 'Canadian',
    nationalId: 'CAN789012',
    program: 'Science',
    admissionYear: 2022,
    currentGradeLevel: '10',
    status: 'Active',
    address: '789 Pine Ln, Springfield',
    studentEmail: 'noah.w@email.com',
    studentPhone: '555-3333',
    parentGuardianName: 'James Williams',
    parentGuardianPhone: '555-3334',
    emergencyContactName: 'James Williams',
    emergencyContactPhone: '555-3334',
    avatarUrl: 'https://picsum.photos/seed/3/100/100',
  },
  {
    studentId: 'S004',
    firstName: 'Emma',
    lastName: 'Brown',
    khmerFirstName: 'អេម៉ា',
    khmerLastName: 'ប្រោន',
    sex: 'Female',
    dateOfBirth: new Date('2008-11-12'),
    nationality: 'Australian',
    nationalId: 'AUS345678',
    program: 'Commerce',
    admissionYear: 2022,
    currentGradeLevel: '10',
    status: 'Active',
    address: '101 Birch Rd, Springfield',
    studentEmail: 'emma.b@email.com',
    studentPhone: '555-4444',
    parentGuardianName: 'Patricia Brown',
    parentGuardianPhone: '555-4445',
    emergencyContactName: 'Patricia Brown',
    emergencyContactPhone: '555-4445',
    avatarUrl: 'https://picsum.photos/seed/4/100/100',
  },
    {
    studentId: 'S005',
    firstName: 'Ava',
    lastName: 'Jones',
    khmerFirstName: 'អាវ៉ា',
    khmerLastName: 'ចូនស៍',
    sex: 'Female',
    dateOfBirth: new Date('2008-05-20'),
    nationality: 'American',
    nationalId: 'USA987654',
    program: 'Arts',
    admissionYear: 2022,
    currentGradeLevel: '10',
    status: 'Active',
    address: '212 Cedar Blvd, Springfield',
    studentEmail: 'ava.j@email.com',
    studentPhone: '555-5555',
    parentGuardianName: 'Jennifer Jones',
    parentGuardianPhone: '555-5556',
    emergencyContactName: 'Jennifer Jones',
    emergencyContactPhone: '555-5556',
    avatarUrl: 'https://picsum.photos/seed/5/100/100',
  },
];


export const assessments: Assessment[] = [
  {
    assessmentId: 'A001',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Algebra Basics',
    category: 'Classwork',
    totalMarks: 25,
    scores: { 'S001': 22, 'S002': 18, 'S003': 24, 'S004': 20, 'S005': 15 },
  },
  {
    assessmentId: 'A002',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Geometry Fundamentals',
    category: 'Unit Assessment',
    totalMarks: 100,
    scores: { 'S001': 88, 'S002': 75, 'S003': 95, 'S004': 82, 'S005': 60 },
  },
  {
    assessmentId: 'A003',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Shakespearean Sonnets',
    category: 'Homework',
    totalMarks: 10,
    scores: { 'S001': 9, 'S002': 10, 'S003': 8, 'S004': 9, 'S005': 10 },
  },
  {
    assessmentId: 'A004',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Modernist Poetry',
    category: 'Unit Assessment',
    totalMarks: 100,
    scores: { 'S001': 85, 'S002': 92, 'S003': 78, 'S004': 88, 'S005': 95 },
  },
  {
    assessmentId: 'A005',
    subjectId: 'SUB001',
    teacherId: 'T001',
    topic: 'Calculus Prep',
    category: 'End-Semester',
    totalMarks: 150,
    scores: { 'S001': 130, 'S002': 110, 'S003': 145, 'S004': 120, 'S005': 95 },
  },
  {
    assessmentId: 'A006',
    subjectId: 'SUB003',
    teacherId: 'T002',
    topic: 'Victorian Novels',
    category: 'End-Semester',
    totalMarks: 150,
    scores: { 'S001': 125, 'S002': 140, 'S003': 115, 'S004': 130, 'S005': 142 },
  },
];
